apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- operator.yaml.yaml
images:
- name: psmdb-operator
  newName: tishina/percona-server-mongodb-operator
  newTag: K8SPSMDB-921_irsa_test_fix_for_cw
